-- schema
DROP SCHEMA IF EXISTS TR_OUTBOX CASCADE;
CREATE SCHEMA TR_OUTBOX;

-- dedup table for processed events
DROP TABLE IF EXISTS TR_OUTBOX.DEDUP_STORE CASCADE;
CREATE TABLE TR_OUTBOX.DEDUP_STORE (
    ID UUID NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    PROCESSED_AT TIMESTAMP WITH TIME ZONE,
    PAYLOAD jsonb NOT NULL,
    EVENT_VERSION integer NOT NULL,
    CONSTRAINT PK_DEDUP PRIMARY KEY (id)
);